name: Matrix Demo
on: push
jobs:
    build:
        runs-on: ${{ matrix.operating-system}}
        strategy:
            matrix:
                node-version: [12,14,16]
                operating-system: [ubuntu-latest,windows-latest]
        steps:
            - name: Get code
              uses: actions@checkout@v3
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: install dependencies
              run: npm ci
            - name: Build Project
              run: npm build run
              